### ISSUE TITLE
./lib/airmon

### ISSUE THREAD

**Issue by shankarshanu** [deltaxflux/fluxion#3]
![screenshot 40](https://cloud.githubusercontent.com/assets/26177345/23587630/ac1be672-01d6-11e7-8505-6f5824efec9e.png)
ths is the error i get sir when i select language

**Comment by sam0hack** [comment]
@shankarshanu this version is not working right now. You can this version https://github.com/sam0hack/fluxion

**Comment by shankarshanu** [comment]
Does this work properly sir

Will I get any error

**Comment by sam0hack** [comment]
@shankarshanu yes it's working.

**Comment by shankarshanu** [comment]
Sir I installed it worked but now it showed it had updates I typed y and
entered now im returning again to terminal

**Comment by sam0hack** [comment]
It's fixed now download and install it again. You can run apt-get purge fluxion for removing it from system if you installed .deb

**Comment by phant0marrow** [comment]
It does not work....running on an rpi3 and from version 131 that had the issue til now, it hasn't changed. The error messages before quitting don't show but it seems like the problem is still very apparent given the auto quit back to the command line....Now I have to re-install the image for something that was "handled".... #pedogate investigation has more stability to be honest.
